//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DichVuThuCungKVH.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTDonDichVu
    {
        public int MaDDV { get; set; }
        public string DichVuDaSuDung { get; set; }
        public Nullable<decimal> ChiPhiPhatSinh { get; set; }
        public Nullable<decimal> ThanhTien { get; set; }
    
        public virtual DichVu DichVu { get; set; }
        public virtual DonDichVu DonDichVu { get; set; }
    }
}
