//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DichVuThuCungKVH.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTPhieuNhan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CTPhieuNhan()
        {
            this.PhieuNhans = new HashSet<PhieuNhan>();
        }
    
        public int MaPhieu { get; set; }
        public string TenTC { get; set; }
        public string HinhAnh { get; set; }
        public string MoTa { get; set; }
        public string MauLong { get; set; }
        public Nullable<bool> Loai { get; set; }
        public Nullable<double> CanNang { get; set; }
        public string TinhTrangTruocTiepNhan { get; set; }
        public string TinhTrangSauTiepNhan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuNhan> PhieuNhans { get; set; }
    }
}
