//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DichVuThuCungKVH.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuNhan
    {
        public int MaPhieu { get; set; }
        public int MaDV { get; set; }
        public string NguoiGiao { get; set; }
        public string NguoiNhan { get; set; }
        public Nullable<System.DateTime> ThoiGian { get; set; }
    
        public virtual CTPhieuNhan CTPhieuNhan { get; set; }
        public virtual DichVu DichVu { get; set; }
    }
}
