//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DichVuThuCungKVH.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuanLi
    {
        public int MaQL { get; set; }
        public string TenQL { get; set; }
        public string ChucVu { get; set; }
        public string ChiNhanh { get; set; }
        public Nullable<int> NamSinh { get; set; }
        public Nullable<int> SDT { get; set; }
        public string DiaChi { get; set; }
        public Nullable<bool> GioiTinh { get; set; }
        public int MaTK { get; set; }
    
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
